name: Delete Untagged Versions
run-name: Delete Untagged Versions

on:
  workflow_call:
    inputs:
      package-name:
        description: Package name
        type: string
        required: true
  workflow_dispatch:
    inputs:
      package-name:
        description: Package name
        type: choice
        options:
          - 'ubuntu'
          - 'node'
          - 'jekyll'
        required: true
        default: 'ubuntu'

jobs:
  delete-untagged-versions:
    name: Delete untagged ${{ inputs.package-name }} versions
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Delete untagged versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ inputs.package-name }}
          package-type: container
          delete-only-untagged-versions: true
